# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TorchTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TorchTest
  pod 'LibTorch', '~>1.7.1'

  target 'TorchTestTests' do
    # Pods for testing
  end

end
